<?php

namespace AppBundle\Repository;

/**
 * BookingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookingRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Retourne le nombre de ticket reservé pour la date $dateTime
     * @param \DateTime $dateTime
     * @return int
     */
    public function countNbTicketPerDate(\DateTime $dateTime)
    {

        $qb = $this->createQueryBuilder('b');
        $qb
            ->select('SUM(b.nbrTicket)')
            ->where('b.dateVisit = :date')
            ->setParameter('date', $dateTime);


        $query = $qb->getQuery();

        return $query->getSingleScalarResult();


    }
}
